// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Tried routing this at Neon's direct (non-pooled) endpoint to dodge a
    // stuck Postgres advisory lock from `migrate deploy` (see git history) —
    // reverted: Vercel's build network (iad1) can't reliably reach that
    // endpoint at all (P1001), a known Neon/Vercel interaction. Back to the
    // same pooled DATABASE_URL the app uses at runtime (src/lib/db.ts). If
    // a stuck advisory lock ever blocks a deploy again (Prisma error P1002,
    // "advisory lock" in the message), the fix is to find and terminate the
    // stale backend session holding it — see pg_locks / pg_terminate_backend
    // — not to switch this back to a direct connection.
    url: process.env["DATABASE_URL"],
  },
});
