// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Supabase (see .env): migrations must go through DIRECT_URL (session-mode
    // pooler, port 5432), not DATABASE_URL (transaction-mode pooler, port
    // 6543, used by the app at runtime — src/lib/db.ts). Supabase's
    // transaction-mode PgBouncer pooler doesn't reliably support the DDL
    // patterns `prisma migrate` issues.
    url: process.env["DIRECT_URL"],
  },
});
